version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb+srv://saudk1539:saud@devbook-api.xotolfa.mongodb.net/?retryWrites=true&w=majority&appName=devbook-api
    depends_on:
      - mongo
    volumes:
      - ./:/app
      - /app/node_modules

  mongo:
    image: mongo:5.0
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data: